### PR TITLE
mongo 3.0.15 seems broken

### PR DESCRIPTION
**Pull request by matu3ba**
Use latest mongo version instead
See https://github.com/docker-library/mongo/issues/164
and https://github.com/ds-wizard/ds-wizard/issues/171

### CODE REVIEW

**Comment by janslifka** [comment]
Hello,

we've just released a new version of DSW today (and this deployment example got updated as well) and I cannot see any issue with mongo. Using these steps:

```
$ git clone git@github.com:ds-wizard/dsw-deployment-example.git
$ cd dsw-deployment-example/
$ docker-compose up -d
```

Everything worked fine. Can you please try it again with the latest version whether it works now?

**Comment by matu3ba** [comment]
Hello,
for me the docker container with the database keeps restarting.
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                            PORTS                    NAMES
70ce1412512d        mongo:3.0.15                         "docker-entrypoint.s…"   4 minutes ago       Restarting (139) 6 seconds ago                             dsw-deployment-example_mongo_1
53b0721f42d8        datastewardshipwizard/client:1.8.1   "/start.sh"              27 hours ago        Up 4 minutes                      0.0.0.0:8080->80/tcp     dsw-deployment-example_dsw_client_1
aba1bc5df1c0        datastewardshipwizard/server:1.8.0   "./dsw-server"           27 hours ago        Up 4 minutes (health: starting)   0.0.0.0:3000->3000/tcp   dsw-deployment-example_dsw_server_1
bd2053452533        datastewardshipwizard/crontab        "/docker-entrypoint …"   27 hours ago        Up 4 minutes (healthy)                                     dsw-deployment-example_dsw_server_worker_1

**Comment by matu3ba** [comment]
Exact same result with database constantly restarting.

**Comment by janslifka** [comment]
I don't like having the mongo version unbound, because it might break with future releases. Also, we need to test everything before updating. I've created a [task in our JIRA](https://ds-wizard.atlassian.net/browse/DSW-470) for the update planned for the next version.

You can use the version that works for you now, and we'll update the example once we are sure that it works well.

**Comment by vknaisl** [comment]
We upgraded it to 4.0.12

**Pull request closed without merging**
